

### 6. Package this set of code in a Docker image that you must push to the AWS elastic container registry ###
### Links to an external site.(ECR) bearing the name 338791806049.dkr.ecr.eu-west-1.amazonaws.com/vlerick_cloud_solutions ###
### and with a tag that starts with your first name. ###

FROM python:3.9.12
LABEL Verena <vqueis@gmail.com>:
ADD main.py /. 
USER root
# Install apt packages and clean up cached files
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo "..." \

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


CMD [ "python", "main.py"]


# Install the AWS CLI and clean up tmp files
RUN wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -O ./awscliv2.zip && \
    unzip awscliv2.zip && \
    ./aws/install
    krm -rf ./aws awscliv2.zip


# For vscode
EXPOSE 3000
# for spark
EXPOSE 4040

# Build the Docker image using the Dockerfile
#$ docker build -t my_image .

# Tag the Docker image with a unique name
#$ docker tag my_image <my_aws_account_id>.dkr.ecr.<my_region>.amazonaws.com/my_repository:latest

# Push the Docker image to ECR
#$ docker push <my_aws_account_id>.dkr.ecr.<my_region>.amazonaws.com/my_repository:latest





